Updates to allow for use of additional PD-CEF fields
sensu/sensu-pagerduty-handler pull request #53
Opened 2023-04-05 04:49 UTC by anguswilliams

- Add `--client-name` and `--sensu-base-url`. If provided, these options add a link to the Sensu dashboard from the Pagerduty Alert.
- Add `--link-annotations` option. If set, this option will any links provided in the check or entity annotations as links in the Pagerduty Event.
- Add ability to template additional [PD-CEF][PD-CEF] Fields from Sensu event data:
  - Add `--use-event-timestamp` option. If set this option will set the `Timestamp` field to the timestamp of the Sensu event.
  - Add `--class-template`, `--group-template` and `--component-template` option. If provided, this option allows for the `Class`, `Group` and `Component` [PD-CEF][PD-CEF] fields to be templated from Sensu event data. Note the `Component` field is set to the Sensu events `.Check.Name` by default if no template is provided to retain compatibility.

2023-04-05 23:14 UTC, anguswilliams commented
@fguimond sorry to bug you, I couldn't find any code owners file and noticed you've merged a change recently. Could I get a review on this?

2023-04-11 15:24 UTC, asachs01 commented
@anguswilliams 👋 can you elaborate on the value these features add to the handler? Is it to be able to take advantage of PD
s event routing/orchestration capabilities?

2023-04-11 21:53 UTC, anguswilliams commented
Hey @asachs01, thanks for the response, thats correct:

For the additional PD-CEF field templates, I have a use case to populate these fields from event labels and route to certain pagerduty services. This means I don't have to send the full event json as `custom_details` to pagerduty and can sanitise the output to be easier to read for the receiving engineer. This is in-line with tools like [Alertmanager](https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config) which make all these fields templatable.

The sensu-base-url part is so you can get back to the sensu dashboard from the pagerduty event. The link-annotations flag allows abitrary links to be added to the PD event via annotations. For example we enforce `check.metadata.annotations.documention` and optionally `entity.metadata.annotations.documention`. They would show up like this in the PD event:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/6813268/231293660-f55e21f7-d2fa-4bb6-a9a6-55db16bb9f92.png">

2023-04-14 16:58 UTC, asachs01 commented
Thanks for the clarification @anguswilliams ! @fguimond is reviewing your changes IIRC and we should have an update on approving the PR soon.

2023-06-12 04:11 UTC, anguswilliams commented
Hey @fguimond / @asachs01, any chance you could take a look at this, I've rebased your latest changes to get rid of the merge conflicts.

2023-06-12 12:09 UTC, asachs01 commented
Hi @anguswilliams I'll have to defer to @fguimond . I no longer have the ability to approve any changes.

2023-08-21 04:55 UTC, anguswilliams commented
@fguimond any chance you could take a look at this?

2024-12-24 04:23 UTC, ManishaKumari295 commented
The current ticket is linked to - https://github.com/sensu/sensu-pagerduty-handler/issues/60

2025-01-07 13:39 UTC, ManishaKumari295 commented
Created an issue for its review and details - https://github.com/sensu/sensu-pagerduty-handler/issues/60

2025-06-18 06:23 UTC, rakibhossainctr requested changes

2025-06-18 06:23 UTC, rakibhossainctr commented on main.go
> +		timestamp = time.Unix(event.Timestamp, 0).Format(time.RFC3339)
The required timestamp format for PagerDuty is 2015-07-17T08:42:58.315+0000 Please update the syntax accordingly, as it currently causes a panic when using the --use-event-timestamp flag

2025-07-07 03:03 UTC, rakibhossainctr approved these changes
LGTM

2026-01-06 11:41 UTC, merged